### ISSUE TITLE
where to obtain APN.mat file?

### ISSUE THREAD

**Issue by litianjun05090** [zjukg/DUET#2]
Already download all the files mentioned but don't know where to obtain APN.mat file

**Comment by BigHyf** [comment]
You can download apn.mat via the following GitHub link:
https://github.com/wenjiaXu/APN-ZSL

**Comment by litianjun05090** [comment]
Thanks,and where to get id2imagepixel.pkl .....

**Comment by BigHyf** [comment]
This data is too large to upload, but it is relatively easy to generate this data.
You can find the image based on the image id of the dataset and run FeatureExtractor through the corresponding swin or deit model

**Comment by Bingyang0410** [comment]
> 
Can you introduce the process of acquiring these pkl files in detail, or give us some reference repo in GitHub? Thanks a lot!

**Comment by BigHyf** [comment]
https://huggingface.co/docs/transformers/model_doc/swin#transformers.SwinModel
It may will help you generate these pkl files.

**Comment by Bingyang0410** [comment]
> https://huggingface.co/docs/transformers/model_doc/swin#transformers.SwinModel It may will help you generate these pkl files.

Got it！ Thank u very much

**Comment by Bingyang0410** [comment]
What's more, there still another question about the output of SwinModel to generate id2imagepixel.pkl. Which parameter I need to choose in the SwinModelOutput?  (such as pooler_output/pooler_output/hidden_states/hidden_states/reshaped_hidden_states)

**Comment by YWS220** [comment]
Thank you for the code. What I want to ask is can you give the exact steps or code to generate the id2imagepixel.pkl file?

**Comment by BigHyf** [comment]
This is a process of generating the embedding according to the image, refer to the above process.

**Comment by passer** [comment]
Thank you very much for sharing, I am a newbie, can you tell me the detailed steps for getting the ID2imagepixel.pkl file?

**Comment by BigHyf** [comment]
> Thank you very much for sharing, I am a newbie, can you tell me the detailed steps for getting the ID2imagepixel.pkl file?

You can follow this Python script(https://github.com/zjukg/DUET/blob/main/cache/generate_embedding.py) to understand the detailed steps. Essentially, the image embedding is obtained through the image url and then saved into a pkl file

**Comment by passer** [comment]
Thank u very much

**Comment by Even008** [comment]
Hello, when I'm running: bash script/AWA2/AWA2_GZSL.sh, I get the following error: RuntimeError: Tensors must have same number of dimensions: got 2 and 4. This is also the case when I run it on the CUB dataset : input = torch.cat((input_v[index].unsqueeze(0), positive_input.unsqueeze(0), negative_input_1_1.unsqueeze(0), negative_input_1_2.unsqueeze(0), negative_input_2_1.unsqueeze(0), negative_input_2_2.unsqueeze(0)), 0)     RuntimeError: Tensors must have same number of dimensions: got 2 and 4. Is there a bug in the experiment?

**Comment by BigHyf** [comment]
It may be an issue with the dataset processing. You can check the dimension information of **input_v[index]**, **positive_input**, and **negative_input_1_1**, and then perform targeted debugging.

**Comment by BigHyf** [comment]
> Hello, when I'm running: bash script/AWA2/AWA2_GZSL.sh, I get the following error: RuntimeError: Tensors must have same number of dimensions: got 2 and 4. This is also the case when I run it on the CUB dataset : input = torch.cat((input_v[index].unsqueeze(0), positive_input.unsqueeze(0), negative_input_1_1.unsqueeze(0), negative_input_1_2.unsqueeze(0), negative_input_2_1.unsqueeze(0), negative_input_2_2.unsqueeze(0)), 0) RuntimeError: Tensors must have same number of dimensions: got 2 and 4. Is there a bug in the experiment?

It may be an issue with the dataset processing. You can check the dimension information of input_v[index], positive_input, and negative_input_1_1, and then perform targeted debugging.

**Comment by Even008** [comment]
> > 您好，当我运行时：bash script/AWA2/AWA2_GZSL.sh，我收到以下错误：运行时错误：张量必须具有相同数量的维度：得到 2 和 4。当我在 CUB 数据集上运行它时也是如此：input = torch.cat（（input_v[index].unsqueeze（0）， positive_input.unsqueeze（0）， negative_input_1_1.unsqueeze（0）， negative_input_1_2.unsqueeze（0）， negative_input_2_1.unsqueeze（0）， negative_input_2_2.unsqueeze（0））， 0） 运行时错误： 张量必须具有相同的维数： 得到 2 和 4。实验中是否有错误？
> 
> 这可能是数据集处理的问题。您可以查看input_v[索引]、positive_input、negative_input_1_1的维度信息，然后进行有针对性的调试。
Thank you very much for your answer, I think there is a problem with this code: input = torch.cat（（input_v[index].unsqueeze（0）， positive_input.unsqueeze（0）， negative_input_1_1.unsqueeze（0）， negative_input_1_2.unsqueeze（0）， negative_input_2_1.unsqueeze（0）， negative_input_2_2.unsqueeze（0））， 0）..
I get their dimensions as：input_v[index]  (3,224,224) and all the others as (1000), after .unsqueeze(0),the shape is a tensor of (1,3,224,224) and (1, 1000), which is obviously not possible to splice with the :torch.cat function. After that I have tried to convert them to tensor of the same dimension, but its form of data interpretation may change. Now I'm wondering if there is something wrong with the code or with the dimension of the generated tensor.Can you help me to discover the problem, thanks a lot!

**Comment by BigHyf** [comment]
> > > 您好，当我运行时：bash script/AWA2/AWA2_GZSL.sh，我收到以下错误：运行时错误：张量必须具有相同数量的维度：得到 2 和 4。当我在 CUB 数据集上运行它时也是如此：input = torch.cat（（input_v[index].unsqueeze（0）， positive_input.unsqueeze（0）， negative_input_1_1.unsqueeze（0）， negative_input_1_2.unsqueeze（0）， negative_input_2_1.unsqueeze（0）， negative_input_2_2.unsqueeze（0））， 0） 运行时错误： 张量必须具有相同的维数： 得到 2 和 4。实验中是否有错误？
> > 
> > 
> > 这可能是数据集处理的问题。您可以查看input_v[索引]、positive_input、negative_input_1_1的维度信息，然后进行有针对性的调试。
> > Thank you very much for your answer, I think there is a problem with this code: input = torch.cat（（input_v[index].unsqueeze（0）， positive_input.unsqueeze（0）， negative_input_1_1.unsqueeze（0）， negative_input_1_2.unsqueeze（0）， negative_input_2_1.unsqueeze（0）， negative_input_2_2.unsqueeze（0））， 0）..
> > I get their dimensions as：input_v[index]  (3,224,224) and all the others as (1000), after .unsqueeze(0),the shape is a tensor of (1,3,224,224) and (1, 1000), which is obviously not possible to splice with the :torch.cat function. After that I have tried to convert them to tensor of the same dimension, but its form of data interpretation may change. Now I'm wondering if there is something wrong with the code or with the dimension of the generated tensor.Can you help me to discover the problem, thanks a lot!

I may have been unclear before, I provided the entire generating of the embedding script. In my impression, generate_embedding.py should not generate an embedding, but a feature (3,224,224). Since it's been a long time, this is a temporary script that we saved for you to refer to to generate ID2imagepixel.pkl, not a complete input/output. 
You can look at the input and implementation process into the forward in the Multi_attention_Model and the implementation process described in our paper to see where the dimension problem lies.

**Comment by BigHyf** [comment]
> > > 您好，当我运行时：bash script/AWA2/AWA2_GZSL.sh，我收到以下错误：运行时错误：张量必须具有相同数量的维度：得到 2 和 4。当我在 CUB 数据集上运行它时也是如此：input = torch.cat（（input_v[index].unsqueeze（0）， positive_input.unsqueeze（0）， negative_input_1_1.unsqueeze（0）， negative_input_1_2.unsqueeze（0）， negative_input_2_1.unsqueeze（0）， negative_input_2_2.unsqueeze（0））， 0） 运行时错误： 张量必须具有相同的维数： 得到 2 和 4。实验中是否有错误？
> > 
> > 
> > 这可能是数据集处理的问题。您可以查看input_v[索引]、positive_input、negative_input_1_1的维度信息，然后进行有针对性的调试。
> > Thank you very much for your answer, I think there is a problem with this code: input = torch.cat（（input_v[index].unsqueeze（0）， positive_input.unsqueeze（0）， negative_input_1_1.unsqueeze（0）， negative_input_1_2.unsqueeze（0）， negative_input_2_1.unsqueeze（0）， negative_input_2_2.unsqueeze（0））， 0）..
> > I get their dimensions as：input_v[index]  (3,224,224) and all the others as (1000), after .unsqueeze(0),the shape is a tensor of (1,3,224,224) and (1, 1000), which is obviously not possible to splice with the :torch.cat function. After that I have tried to convert them to tensor of the same dimension, but its form of data interpretation may change. Now I'm wondering if there is something wrong with the code or with the dimension of the generated tensor.Can you help me to discover the problem, thanks a lot!

I may have been unclear before, I provided the entire generating of the embedding script. In my impression, generate_embedding.py should not generate a embedding, but a feature (3,224,224). Since it's been a long time, this is a temporary script that we saved for you to refer to to generate ID2imagepixel.pkl, not a complete input/output. 
You can look at the input and implementation process into the forward in the Multi_attention_Model and the implementation process described in our paper to see where the dimension problem lies.

**Comment by wangwangwangj** [comment]
> > > 您好，当我运行时：bash script/AWA2/AWA2_GZSL.sh，我收到以下错误：运行时错误：张量必须具有相同数量的维度：得到 2 和 4。当我在 CUB 数据集上运行它时也是如此：input = torch.cat（（input_v[index].unsqueeze（0）， positive_input.unsqueeze（0）， negative_input_1_1.unsqueeze（0）， negative_input_1_2.unsqueeze（0）， negative_input_2_1.unsqueeze（0）， negative_input_2_2.unsqueeze（0））， 0） 运行时错误： 张量必须具有相同的维数： 得到 2 和 4。实验中是否有错误？
> > 
> > 
> > 这可能是数据集处理的问题。您可以查看input_v[索引]、positive_input、negative_input_1_1的维度信息，然后进行有针对性的调试。非常感谢您的回答，我认为这段代码有问题：input = torch.cat（（input_v[index].unsqueeze（0）， positive_input.unsqueeze（0）， negative_input_1_1.unsqueeze（0）， negative_input_1_2.unsqueeze（0）， negative_input_2_1.unsqueeze（0）， negative_input_2_2.unsqueeze（0））， 0）..我得到它们的维度为：input_v[index]（3,224,224），所有其他维度为（1000），在.unsqueeze（0）之后，形状是（1,3,224,224）和（1， 1000）的张量，这显然不可能与：torch.cat 函数拼接。之后，我尝试将它们转换为相同维度的张量，但其数据解释的形式可能会发生变化。现在我想知道代码或生成的张量的维度是否有问题。你能帮我发现问题吗，非常感谢！


Hello, I have the same problem as you, did you solve it? If you don't mind, can you tell us how it was solved, thank you very much!

**Comment by hackerchenzhuo** [comment]
Hi everyone, thanks for your attention.

Our cache data for (CUB, AWA, SUN) are now available [here](https://pan.baidu.com/s/13oyLDNm6uoYpVgcMitrY-A) (Baidu cloud, 19.89G, Code: s07d).

@litianjun05090 @Bingyang0410 @wangwangwangj @Even008 @passer

**Comment by Even008** [comment]
Hi, I would like to ask one other question, the splitting standard we usually use is xlsa17, but how is the file  'att_splits.mat ' generated? I didn't find the method in the original paper!  Can you explain this, thank you very much!
