### ISSUE TITLE
Can you upload the complete code and files to google disk? 

### ISSUE THREAD

**Issue by xiaoxiaokaiyan** [zjukg/DUET#4]
Can you upload the complete code and files to google disk?

**Comment by hackerchenzhuo** [comment]
I’m sorry that the size of my Google Cloud Drive is only 15G (with 5G remaining) and cannot store so much data

**Comment by Chunyu123** [comment]
Hello, sorry for the interruption. There are attri_name and binary_att files included in att_splits.mat, may I know how to get them? And could you please provide them?

**Comment by hackerchenzhuo** [comment]
@Chunyu123 Please refer to [OntoZSL](https://github.com/genggengcss/OntoZSL) and [Resources_for_KZSL](https://github.com/China-UK-ZSL/Resources_for_KZSL)

**Comment by Chunyu123** [comment]
Sorry to bother you, I'd like to double check with you that my understanding is correct. The threshold is calculated from the attribute vectors without normalization (i.e., ‘original_att’ in ‘att_splits.mat’), and the method is to calculate the mean of all attributes in all categories, not for each attribute. The threshold is then applied to the normalized attribute vectors (i.e., ‘att’ in ‘att_splits.mat’) to achieve the classification of the attributes. Is my understanding correct?

In addition, may I ask where did you get the attribute name (‘attri_name’ in ‘att_splits.mat’) from?

**Comment by hackerchenzhuo** [comment]
- It should be the mean of **each** attribute. You are right.
- You can also try to take the global average as a threshold, each with its own benefits
- The attribute name comes from the original ZSL datasets. See [OntoZSL](https://github.com/genggengcss/OntoZSL) and [Resources_for_KZSL](https://github.com/China-UK-ZSL/Resources_for_KZSL) and APN. 

It's been a while, and I don't quite remember the specific details.

**Comment by Chunyu123** [comment]
Thank you for your reply.
