### ISSUE TITLE
How to get pretrained weight for BertTokenizer?

### ISSUE THREAD

**Issue by TAKELAMAG** [zjukg/DUET#5]
When I was doing experiments on the CUB dataset, I found that the pre-training weight of BertTokenizer needs to be loaded in the main.py. How can I get the pre-training weight?
`if opt.dataset == "CUB":
        mask_for_predict = torch.zeros(30522)
        tokenizer = BertTokenizer.from_pretrained("/home/hyf/data/PLMs/bert-base-uncased", do_lower_case=True)`

**Comment by hackerchenzhuo** [comment]
Hi @TAKELAMAG ,

Thank you for your inquiry. In the code snippet you've shared, we are utilizing the default **bert-base-uncased** tokenizer. There haven't been any additional updates to the vocabulary or further pre-training performed on this tokenizer. The prefix **/home/hyf/data/PLMs/** is the path where this default BertTokenizer is located on our system.

You're free to update and modify the tokenizer's vocabulary as per your requirements. Such adaptations can be made based on the specifics of your use case.

If you need further assistance or have more questions, feel free to ask!

Best regards.

**Comment by TAKELAMAG** [comment]
Dear Zhou Chen,



Thanks for your help. I have solved the problem.


Best regards.  







---- Replied Message ----
| From | Zhuo ***@***.***> |
| Date | 4/11/2024 12:36 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [zjukg/DUET] How to get pretrained weight for BertTokenizer? (Issue #5) |

Hi @TAKELAMAG ,

Thank you for your inquiry. In the code snippet you've shared, we are utilizing the default bert-base-uncased tokenizer. There haven't been any additional updates to the vocabulary or further pre-training performed on this tokenizer. The prefix /home/hyf/data/PLMs/ is the path where this default BertTokenizer is located on our system.

You're free to update and modify the tokenizer's vocabulary as per your requirements. Such adaptations can be made based on the specifics of your use case.

If you need further assistance or have more questions, feel free to ask!

Best regards.
